### ISSUE TITLE
USER STORY: Add Painting Form

### ISSUE THREAD

**Issue by jtimlin** [jindah/masterpiece#11]
As a **Site User** I can **upload my own paintings through an easy form** so that **I can share them with other users.**

### Acceptance Criteria
- A logged in Site User should have the option to upload a painting after clicking the "Add Painting" button that appears after logging in on the home page and in the nav bar.
- The click of the button should lead the Site User to a painting upload form.
- After filling out the form with the required data, the Site User should be able to post their painting with the "Publish" button below.
- With the click on the submit button, the Site User should be notified if the post was successful or not. On an error it should not get posted.
- The painting should then be available from the User Profile page and the Gallery page.

### Tasks
- [x]  Create PaintingForm in forms.py
- [x]  Create AddPainting Class in views.py
- [x]  Create add_painting.html template
- [x]  Create validation steps for the painting form to ensure correct input
- [x]  Wire up URLs and templates
- [x]  Create post confirmation
