### ISSUE TITLE
USER STORY: Three latest Art Pieces

### ISSUE THREAD

**Issue by jtimlin** [jindah/masterpiece#12]
As a **Site User** I can **scroll through a list of three paintings** so that **I can get a quick overview of masterpieces.**

### Acceptance Criteria
As a Site User, I should see a list of all masterpieces ordered by the newest first on the home page.
The list should consist of cards, where each card has a title, painting and a link to the painting page.

### Tasks
- [x]  Create PaintingList class in views.py
- [x]  Create index.html in templates
- [x]  Create a UX-friendly card layout with Bootstrap 5
