### ISSUE TITLE
USER STORY: Viewing Users Own Paintings

### ISSUE THREAD

**Issue by jtimlin** [jindah/masterpiece#14]
As a **Site User** I can **view my own masterpieces** so that **I can review and manage the masterpieces I have created**

### Acceptance Criteria
- A logged in Site User should be able to see a "Profile" button in the nav bar.
- The click of the button should lead the Site User to their "Profile" page.
- This page should show all the paintings the Site User has created and some personal information if they want to.
- On click on a specific painting the Site User should be lead this painting detail page.

### Tasks
- [x]  Create my_paintings.html in templates
- [x]  Create a user friendly pagination to show the profiles details and paintings
- [x]  Create MyPaintings in views.py
- [x]  Create a hidden "Profile" button, which shows for the logged in Site User
