### ISSUE TITLE
USER STORY: View Liked Masterpieces

### ISSUE THREAD

**Issue by jtimlin** [jindah/masterpiece#15]
As a **Site User** I can **view all masterpieces I liked on one page** so that **I can sort out my favorite paintings**

### Acceptance Criteria
- A logged in Site User should see a "Likes" button in the nav bar.
- The click of the button should lead the Site User to their "Likes" page.
- The "Likes" page renders all paintings the Site User has liked in a paginated view.
- On click of each of the painting the Site User should be lead to the details page of the painting they selected.

### Tasks
- [x]  Create Likes.html in templates
- [x]  Create Likes in views.py
- [x]  Create a "Like" button that shows for logged in Site Users so they can like paintings
