### ISSUE TITLE
USER STORY: Gallery

### ISSUE THREAD

**Issue by jtimlin** [jindah/masterpiece#16]
As a **Site User** I can **scroll through a list of paintings** so that **I can get a overview of many masterpieces.

### Acceptance Criteria
As a Site User, I should see a paginated list of all masterpieces ordered by the newest first on the gallery page.
The list should consist of cards, where each card has a title, painting and a short description (if available).

### Tasks
- [x]  Create Gallery class in views.py
- [x]  Create gallery.html in templates
- [x]  Create a UX-friendly card layout with Bootstrap 5
