### ISSUE TITLE
USER STORY: My Account Page

### ISSUE THREAD

**Issue by jtimlin** [jindah/masterpiece#18]
As a **Site User** I can **see my account info** so that **I can edit it when needed**

### Acceptance Criteria
As a Site User, I should see a page where users info is displayed

### Tasks
- [ ]  Create MyAccount class in views.py
- [ ]  Create account.html in templates
- [ ]  Create a UX-friendly layout with Bootstrap 5
- [ ]  Wire up views and urls
