### ISSUE TITLE
USER STORY: Manage Posts as Admin

### ISSUE THREAD

**Issue by jtimlin** [jindah/masterpiece#2]
As a **Site Admin** I can **create, read, update and delete posts** so that **I can manage my art gallery content**

### Acceptance Criteria
a. As a logged in Admin, I can see a list of all paintings and comments on the admin panel.
b. As Admin I can then create, update and delete any category, recipe or comment.

### Tasks
- [x]  Create painting models.
- [x]  Create a superuser.
- [x]  Set up the connection between Paintings and Comments.
- [x]  Install summernote a better admin UX
