### ISSUE TITLE
USER STORY: User registration

### ISSUE THREAD

**Issue by jtimlin** [jindah/masterpiece#3]
As a **Site User** I can **register myself to this website** so that **i can upload/update/delete my own paintings and comments.**

### Acceptance Criteria
- As a Site User I should see a "Sign Up" button on the homepage.
- The click of the button should lead the Site User to the SignUp page.
- After filling in the details a new account should be created for the Site User.

### Tasks
- [x]  Add a SignUp button to the nav bar, which is only visible for logged out Site Users
- [x]  Create SignUp.html in templates
- [x]  Create success or error messages for the registration process
