### ISSUE TITLE
USER STORY: Like Paintings

### ISSUE THREAD

**Issue by jtimlin** [jindah/masterpiece#6]
As a **Site User** I can **"Like" a painting** so that **I can sort out paintings I like from others.**

### Acceptance Criteria
- As a logged in Site User I should be able to "like" a painting with a heart icon.
- The click on the icon should add the painting to the Site Users "Likes" page.
- Another click on the icon should remove the painting from their "Likes" page.
- A notification should appear for the Site User to confirm the adding or removing of a painting to their liked page.

### Tasks
- [x]  Add "Likes" icon to the painting details page which only appears for logged in Site Users
- [x]  Create Likes in views.py
- [x]  Toggle the "Likes" icon from border to solid
