### ISSUE TITLE
USER STORY: Edit & Delete Paintings

### ISSUE THREAD

**Issue by jtimlin** [jindah/masterpiece#7]
As a **Site User** I can **edit and delete my own paintings** so that **I can keep my details of paintings up to date or remove them**

#### Edit:
- A logged in Site User should see an "Edit" button under paintings they have created.
- The click of the button should lead the Site User to an edit form, which is prepopulated with the details.
- The "Confirm" button should lead the Site User back to the details page and update their paintings info in the database.
- A success or error message should be displayed.

#### Delete:
- A logged in Site User should see a "Delete" button under paintings they have created.
- The click on the button should ask the Site User to confirm their removal.
- The "Confirm" button should lead the Site User back to the User Profile page..
- A success or error message should be displayed.

### Tasks
- [x]  Create EditPainting and DeletePainting classes in views,py
- [x]  Ensure that the Site User is logged in and can only edit/delete their own paintings
- [x]  Add the "Edit" and "Delete" buttons to the Detail template. Those buttons should only appear if the user is logged in and owns the painting
- [x]  Create EditPainting.html and DeletePainting.html templates
- [x]  Wire up URLs and templates
- [x]  Create edit/delete confirmation
